// supabase/functions/backfill-creator-plans-stripe/index.ts
import Stripe from "https://esm.sh/stripe@14.21.0?target=deno";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1?target=deno";

type Body = { admin_token: string; limit?: number };

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
      "Access-Control-Allow-Methods": "POST, OPTIONS",
      };

      function json(status: number, body: unknown) {
        return new Response(JSON.stringify(body), {
            status,
                headers: { ...corsHeaders, "content-type": "application/json" },
                  });
                  }

                  function env(...keys: string[]) {
                    for (const k of keys) {
                        const v = Deno.env.get(k);
                            if (v && v.trim().length) return v;
                              }
                                return "";
                                }

                                function toMinorUnit(price_cents: number) {
                                  const n = Number(price_cents);
                                    if (!Number.isFinite(n) || n < 0) throw new Error("Invalid price_cents");
                                      return Math.trunc(n);
                                      }

                                      function intervalFromBillingPeriod(bp: string) {
                                        const x = (bp || "").toLowerCase();
                                          if (x === "yearly" || x === "year") return { interval: "year" as const, interval_count: 1 };
                                            return { interval: "month" as const, interval_count: 1 };
                                            }

                                            Deno.serve(async (req) => {
                                              if (req.method === "OPTIONS") return new Response("ok", { status: 200, headers: corsHeaders });
                                                if (req.method !== "POST") return json(405, { error: "Method not allowed" });

                                                  try {
                                                      const STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY", "OP_STRIPE_SECRET_KEY");
                                                          const SUPABASE_URL = env("SUPABASE_URL");
                                                              const SUPABASE_SERVICE_ROLE_KEY = env("SUPABASE_SERVICE_ROLE_KEY");
                                                                  const ADMIN_TOKEN = env("ADMIN_TOKEN");
                                                                      if (!STRIPE_SECRET_KEY || !SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY || !ADMIN_TOKEN) {
                                                                            return json(500, { error: "Missing env (need STRIPE_SECRET_KEY, SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, ADMIN_TOKEN)" });
                                                                                }

                                                                                    const body: Body = await req.json();
                                                                                        if (!body?.admin_token || body.admin_token !== ADMIN_TOKEN) {
                                                                                              return json(403, { error: "Forbidden" });
                                                                                                  }

                                                                                                      const limit = Math.max(1, Math.min(200, Number(body.limit ?? 50)));
                                                                                                          const supa = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
                                                                                                              const stripe = new Stripe(STRIPE_SECRET_KEY, { apiVersion: "2023-10-16" });

                                                                                                                  const { data: plans, error } = await supa
                                                                                                                        .from("creator_plans")
                                                                                                                              .select("id, creator_id, name, description, price_cents, currency, billing_period, stripe_product_id, stripe_price_id, is_active")
                                                                                                                                    .is("stripe_price_id", null)
                                                                                                                                          .eq("is_active", true)
                                                                                                                                                .order("created_at", { ascending: true })
                                                                                                                                                      .limit(limit);

                                                                                                                                                          if (error) return json(500, { error: "DB read error", details: error.message });
                                                                                                                                                              if (!plans || plans.length === 0) return json(200, { ok: true, processed: 0 });

                                                                                                                                                                  let processed = 0;
                                                                                                                                                                      const results: Array<{ plan_id: string; product?: string; price?: string; error?: string }> = [];

                                                                                                                                                                          for (const p of plans) {
                                                                                                                                                                                try {
                                                                                                                                                                                        let productId = (p.stripe_product_id || "").trim();
                                                                                                                                                                                                let priceId = (p.stripe_price_id || "").trim();

                                                                                                                                                                                                        if (!productId) {
                                                                                                                                                                                                                  const product = await stripe.products.create(
                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                            name: p.name,
                                                                                                                                                                                                                                                          description: p.description || undefined,
                                                                                                                                                                                                                                                                        metadata: { kind: "creator_plan", plan_id: p.id, creator_id: p.creator_id },
                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                { idempotencyKey: `op_prod_${p.id}` },
                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                    productId = product.id;

                                                                                                                                                                                                                                                                                                                              const { error: up1 } = await supa
                                                                                                                                                                                                                                                                                                                                          .from("creator_plans")
                                                                                                                                                                                                                                                                                                                                                      .update({ stripe_product_id: productId, updated_at: new Date().toISOString() })
                                                                                                                                                                                                                                                                                                                                                                  .eq("id", p.id);
                                                                                                                                                                                                                                                                                                                                                                            if (up1) throw new Error(`save stripe_product_id failed: ${up1.message}`);
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                            if (!priceId) {
                                                                                                                                                                                                                                                                                                                                                                                                      const unit_amount = toMinorUnit(p.price_cents);
                                                                                                                                                                                                                                                                                                                                                                                                                const { interval, interval_count } = intervalFromBillingPeriod(p.billing_period);

                                                                                                                                                                                                                                                                                                                                                                                                                          const price = await stripe.prices.create(
                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    product: productId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  currency: (p.currency || "eur").toLowerCase(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                unit_amount,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              recurring: { interval, interval_count },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            nickname: `${p.name} (${p.billing_period})`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          metadata: { kind: "creator_plan", plan_id: p.id, creator_id: p.creator_id },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  { idempotencyKey: `op_price_${p.id}_${unit_amount}_${interval}_${interval_count}` },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      priceId = price.id;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const { error: up2 } = await supa
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .from("creator_plans")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .update({ stripe_price_id: priceId, updated_at: new Date().toISOString() })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .eq("id", p.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (up2) throw new Error(`save stripe_price_id failed: ${up2.message}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              processed++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      results.push({ plan_id: p.id, product: productId, price: priceId });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    results.push({ plan_id: p.id, error: String(e?.message ?? e) });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return json(200, { ok: true, processed, results });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.error("backfill-creator-plans-stripe error:", e);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return json(500, { error: "Internal error", details: String(e?.message ?? e) });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });